import type { Metadata } from 'next';

import { ReactNode } from 'react';

import styles from './layout.module.scss';
import '@/shared/config/styles/index.scss';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
    return (
        <html lang="en">
            <body className={styles.root}>
                <main className={styles.main}>{children}</main>
            </body>
        </html>
    );
}
