import type { Metadata } from 'next';

import { ReactNode } from 'react';

import { Providers } from '@/app/providers';
import '@/shared/config/styles/index.scss';
import { HeaderServer } from '@/widgets/headerServer/HeaderServer';
import { ModalHost } from '@/widgets/modalHost/ModalHost';
import { NotificationCenter } from '@/widgets/notificationCenter/NotificationCenter';

import styles from './layout.module.scss';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default async function RootLayout({ children }: { children: ReactNode }) {
    return (
        <html lang="en">
            <body className={styles.root}>
                <Providers>
                    <HeaderServer />
                    <main className={styles.main}>{children}</main>
                    <ModalHost />
                    <NotificationCenter />
                </Providers>
            </body>
        </html>
    );
}
